apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
      - name: library
        image: library-tomcat:8.5.47
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
      - name: myssql-libray
        image: library-mysql:5.7.28
        imagePullPolicy: Never
        ports:
        - containerPort: 3306


